### ISSUE TITLE
Moving Text on hover

### ISSUE THREAD

**Issue by madhavanand-github** [ByteGrad/CSS-Course#4]
Using what learn't in Project, Social Editor.
I Tried replicating a cool button saw in a YouTube video([Link](https://youtu.be/-vDf7xDVDe0?t=16)).

Took a screenshot and simply started coding.
Surprisingly, I was able to create it. Thanks to you. First. :)

🟥 **But the problem is** "When I hove the buttons, the text above it also moves".
May you please tell me how to fix that and logic behind that solution. 

**Code Pen Link** — https://codepen.io/madhav_anand/pen/bGoZYaJ

**Comment by ByteGrad** [comment]
Hi Madhav,

The text above the buttons moves up because the hovered button pushes it up through increased padding. An increase in padding can affect the elements around it.

When hovering the button, instead of changing the 'padding', you could try the following:

```
button:hover {
  transform: scale(1.1);
}
```

This won't push up the button, because 'transform' doesn't affect the other elements around it.

This is tricky to know though, and I only know it because of years of trial and error.

**Comment by madhavanand-github** [comment]
Thanks it worked.

How about a scenario when we want to scale a specific property(s) instead of all. Like in this case, I want to scale up padding, not the text and icon. Is there any way for this ?

**Comment by ByteGrad** [comment]
Technically possible, but it’s very complicated and probably not worth it.

Some other options instead of using “transform: scale”:

1) Use position: absolute for the heading, then it won’t be affected by
elements around it,
2) Use position: absolute for the buttons, then they won’t affect elements
around it.

These have other downsides, though. Like they might change their position,
so you have to use the offset-properties (top, left, bottom, right) to
position them properly again.
