### ISSUE TITLE
BetterPhotos - nav__icon line-height overridden by font awesome css

### ISSUE THREAD

**Issue by gajimicu** [ByteGrad/CSS-Course#6]
I love the class, I'm learning a lot!

I'm at Video 19, 12min30sec and defining a line height of 65px for the nav icons is does not center them.
You can see here that font awesome css is overriding the line height with its own property.
![Screen Shot 2022-02-23 at 12 18 29 PM](https://user-images.githubusercontent.com/6078559/155309423-e1463cd9-206b-49cb-9b1f-79dfb342a672.png)

I double checked my code and it looks like I did everything correctly. But let me know if I should send you files or something.
thanks for your help!

**Comment by ByteGrad** [comment]
Hi there, great to hear you like the course.

You have an interesting bug. I just checked the project and it still works for me. 

My best guess is that this is due to the order in which you are linking to your stylesheet and to FontAwesome's stylesheet in your HTML. 

Make sure the link to your stylesheet comes after the FontAwesome stylesheet:
![stylesheets-order](https://user-images.githubusercontent.com/82057865/155317541-3b5c20f6-7f53-47ea-81f2-1bb92d14815b.png)

I get the same bug as you when I flip the order.

The browser can only apply one of the declarations with regard to line-height here, so it needs to pick which one. The general rule is that it picks the latter one.

**Comment by gajimicu** [comment]
That solved it right away, thanks a lot!
And it's a great thing to keep in mind, always load your own stylesheet after all the third party ones so your styles apply.
